# Dog Breeds Classification using Pretrained Resnet

In [ ]:
from torchvision import models 
from torchvision import transforms
import torch

In [2]:
resnet = models.resnet101(pretrained=True)

In [3]:
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
    ])

# Using My puppy's image

In [4]:
from PIL import Image
img = Image.open(".\my_puppy.jpg")

In [5]:
img_t = preprocess(img)
img_t

tensor([[[ 0.7077,  0.6734,  0.7762,  ...,  1.4440,  1.3242,  1.0844],
         [ 0.6221,  0.5878,  0.6906,  ...,  1.4440,  1.3927,  1.2728],
         [ 0.6734,  0.6734,  0.7248,  ...,  1.3584,  1.4269,  1.3584],
         ...,
         [ 0.9817,  0.9988,  1.0159,  ..., -0.4911, -0.5253, -0.6281],
         [ 0.9988,  1.0331,  1.0331,  ..., -0.5767, -0.7137, -0.7137],
         [ 0.9988,  1.0331,  1.0159,  ..., -0.6452, -0.6794, -0.6452]],

        [[ 0.8179,  0.7654,  0.8704,  ...,  1.4832,  1.3606,  1.0805],
         [ 0.7304,  0.6954,  0.8004,  ...,  1.5007,  1.4482,  1.2906],
         [ 0.8004,  0.8179,  0.8704,  ...,  1.3957,  1.4832,  1.4132],
         ...,
         [ 0.6078,  0.6254,  0.6779,  ..., -0.8277, -0.8627, -0.9678],
         [ 0.6429,  0.6779,  0.6954,  ..., -0.9153, -1.0553, -1.0553],
         [ 0.6429,  0.6779,  0.6954,  ..., -0.9853, -1.0203, -0.9853]],

        [[ 1.1237,  1.1062,  1.2108,  ...,  1.7163,  1.5768,  1.3154],
         [ 1.0191,  1.0191,  1.1237,  ...,  1

In [6]:
batch_t = torch.unsqueeze(img_t, 0)
batch_t

tensor([[[[ 0.7077,  0.6734,  0.7762,  ...,  1.4440,  1.3242,  1.0844],
          [ 0.6221,  0.5878,  0.6906,  ...,  1.4440,  1.3927,  1.2728],
          [ 0.6734,  0.6734,  0.7248,  ...,  1.3584,  1.4269,  1.3584],
          ...,
          [ 0.9817,  0.9988,  1.0159,  ..., -0.4911, -0.5253, -0.6281],
          [ 0.9988,  1.0331,  1.0331,  ..., -0.5767, -0.7137, -0.7137],
          [ 0.9988,  1.0331,  1.0159,  ..., -0.6452, -0.6794, -0.6452]],

         [[ 0.8179,  0.7654,  0.8704,  ...,  1.4832,  1.3606,  1.0805],
          [ 0.7304,  0.6954,  0.8004,  ...,  1.5007,  1.4482,  1.2906],
          [ 0.8004,  0.8179,  0.8704,  ...,  1.3957,  1.4832,  1.4132],
          ...,
          [ 0.6078,  0.6254,  0.6779,  ..., -0.8277, -0.8627, -0.9678],
          [ 0.6429,  0.6779,  0.6954,  ..., -0.9153, -1.0553, -1.0553],
          [ 0.6429,  0.6779,  0.6954,  ..., -0.9853, -1.0203, -0.9853]],

         [[ 1.1237,  1.1062,  1.2108,  ...,  1.7163,  1.5768,  1.3154],
          [ 1.0191,  1.0191,  

In [7]:
resnet.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [8]:
out = resnet(batch_t)
out

tensor([[-4.5487e+00, -4.1952e+00, -2.1978e+00, -3.0708e+00, -2.7482e+00,
         -2.6653e+00, -3.7002e+00,  5.8382e-02,  2.4834e+00,  4.5238e+00,
         -2.8163e+00, -3.5689e+00, -1.9650e+00, -3.7485e+00, -2.3131e+00,
          1.0234e+00, -3.1106e+00, -1.5194e+00, -3.2642e+00, -8.7490e-01,
         -1.1333e-01, -3.5390e+00, -2.8182e+00, -1.8105e+00,  3.0279e-01,
         -2.6219e+00, -1.5401e+00, -2.5338e+00, -2.0610e+00, -2.9696e+00,
         -2.6311e+00, -6.1914e-01,  1.8820e+00, -4.3810e-01, -2.0022e+00,
         -1.4907e+00,  1.0219e+00, -1.2504e-01,  2.6015e-01, -2.9733e+00,
         -2.3787e+00, -6.0175e-01, -1.9123e-01, -8.9318e-01, -2.7653e-01,
         -4.3991e-01, -3.0433e+00, -3.9233e+00, -2.9534e+00, -1.0280e+00,
         -9.2005e-01,  5.7899e-01,  1.3239e+00,  1.2595e+00,  3.3379e+00,
         -2.8891e+00, -1.1417e+00, -2.0274e+00, -7.1711e-01, -8.8450e-01,
          1.6788e+00,  3.8595e-01, -4.4236e-01,  4.6500e-01, -1.7059e+00,
         -4.2934e-01,  2.4989e-01,  8.

In [9]:
with open('.\\imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [10]:
_, index = torch.max(out, 1)

In [11]:
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index[0]], percentage[index[0]].item()

('toy poodle', 71.00991821289062)

In [12]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('toy poodle', 71.00991821289062),
 ('miniature poodle', 26.6029052734375),
 ('Airedale, Airedale terrier', 0.8777164220809937),
 ('Dandie Dinmont, Dandie Dinmont terrier', 0.5384358763694763),
 ('Lakeland terrier', 0.3298969268798828)]